version: '3.6'
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/app'
    ports:
      - 5008:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - RECEIPTS_PATH=https://kalkuli-receipts-hom.herokuapp.com
      - EXPORT_PATH=https://kalkuli-export.herokuapp.com
      - EXTRACTION_PATH=https://kalkuli-extraction.herokuapp.com
      - REPORTS_PATH=https://kalkuli-reports-hom.herokuapp.com
      - USERS_PATH=https://kalkuli-users-hom.herokuapp.com
      - INTERPRETATION_PATH=https://g1b41i0pn3.execute-api.sa-east-1.amazonaws.com/hom